config/routes.rb
Limsv1::Application.routes.draw do
  
  devise_for :users

  resources :spectros

  resources :rnaseqs

  resources :seizespyros

  resources :metagenomes

  resources :genomes

  resources :data

  resources :submissions

  resources :sequencings

  resources :em_pcrs

  resources :libraries

  resources :extractions

  get "cultures/show"
  
  resources :cultures
  
  

  resources :experiments
  resources :elements 

  resources :users

  resources :projects
  resources :home
  
 
  get "home/index"
  get "projects/destroy"

root :to => 'home#index'

end

app/models/sequencing.rb
class Sequencing < ActiveRecord::Base
  belongs_to :element  
  attr_accessible :empcr_assoc, :distance_cassure, :element_id, :paired_end, :sequencing_name
  
  
  validates_presence_of :empcr_assoc
  
  #see  form_edit
def display_name
 "#{sequencing_name}"
end

end

app/controllers/sequencings_controller.rb
class SequencingsController < ApplicationController
  
   #helper from devise
  before_filter :authenticate_user!
  
      #cancan permet d'afficher uniqeuement si authoriser dans ability.rb
 load_and_authorize_resource
  
  # GET /sequencings
  # GET /sequencings.json
  def index
    @sequencings = Sequencing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sequencings }
    end
  end

  # GET /sequencings/1
  # GET /sequencings/1.json
  def show
    @sequencing = Sequencing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sequencing }
    end
  end

  # GET /sequencings/new
  # GET /sequencings/new.json
  def new
    @sequencing = Sequencing.new
     
   #params :elt from elementcontroller
     @project_associe_id=params[:elt][:cp]  # va servir ds extraction _form view
      @e=params[:elt] 
      @e.delete(:cp)      
    flash[:elt]=@e  #from elementcontroller used for next action :create

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sequencing }
    end
  end

  # GET /sequencings/1/edit
  def edit
    @sequencing = Sequencing.find(params[:id])
  end

  # POST /sequencings
  # POST /sequencings.json
  
   #renseigne l'id de l element associé...si sequencing n est pas sauvé, l'element nouvellement cree est effacé
  
  
  def create
    @sequencing = Sequencing.new(params[:sequencing])
    
     @elt=flash[:elt]
    @element = Element.new(@elt)
    @element.element_name= @sequencing.sequencing_name
    
    #cf uniqueness of element_name ds model
    if  ! (@element.valid?)
      if (@element.projects.blank?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
      else
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! name already used '
        return     
    end
    end
    
    
       #cf presence of _assoc ds model
    if  ! (@sequencing.valid?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
    end
    
    
    if (@sequencing.paired_end=="no" &&  ! (@sequencing.distance_cassure.blank?))
    redirect_to :controller => 'elements', :action => 'new', :notice => " element has not been saved - 'distance cassure' can be filled only if PET seq "
        return
    
  end
    
    @element.save    
    #@sequencing.sequencing_name=flash[:elt][:element_name] 
    #permet d'associer elt a seq pour projet::detail elt
    @sequencing.element_id= Element.last.id
  
  
  
  
    respond_to do |format|
      if @sequencing.save
        format.html { redirect_to @sequencing, notice: 'Sequencing was successfully created.' }
        format.json { render json: @sequencing, status: :created, location: @sequencing }
      else
    
        format.html { render action: "new" }
        format.json { render json: @sequencing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sequencings/1
  # PUT /sequencings/1.json
  def update
    @sequencing = Sequencing.find(params[:id])

    respond_to do |format|
      if @sequencing.update_attributes(params[:sequencing])
        format.html { redirect_to @sequencing, notice: 'Sequencing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sequencing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequencings/1
  # DELETE /sequencings/1.json
  def destroy
    @sequencing = Sequencing.find(params[:id])
    @sequencing.destroy

    respond_to do |format|
      format.html { redirect_to sequencings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sequencings_helper.rb
module SequencingsHelper
end

app/views/sequencings/_form.html.erb
<%= semantic_form_for @sequencing , :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :sequencing_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sequencing_name, :class => 'text_field'  %>
    </div>
  </div>
  

  
  <div class="control-group">    
    <div class="controls">
     <!--method ds helper -->
    <%= f.input :empcr_assoc, :as => :radio, :collection => filtre_elt_associe(@project_associe_id,"EM_PCR") %>       
    </div>
  </div>
  
  <div class="control-group">  
    <div class="controls">
    <%= f.input :paired_end, :as => :radio, :collection => ["yes","no"] %>
    </div>
  </div>
  
  <div class="control-group">    
    <div class="controls">
         <%= f.input :distance_cassure %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sequencings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sequencings/_form_edit.html.erb
<%= semantic_form_for @sequencing , :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :sequencing_name, :class => 'control-label' %>
    <div class="controls">
      <%= @sequencing.sequencing_name  %>
    </div>
  </div>
  

  
  <div class="control-group">    
    <div class="controls">
     <!--method ds helper -->
    <%= f.input :empcr_assoc, :as => :radio, :collection => EmPcr.all.collect {|el| el.EM_PCR_name}
 %>       
    </div>
  </div>
  
  <div class="control-group">  
    <div class="controls">
    <%= f.input :paired_end, :as => :radio, :collection => ["yes","no"] %>
    </div>
  </div>
  
  <div class="control-group">    
    <div class="controls">
         <%= f.input :distance_cassure %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                elements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sequencings/edit.html.erb
<%- model_class = @sequencing.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/sequencings/index.html.erb
<%- model_class = Sequencing.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sequencing_name) %></th>
      <th><%= model_class.human_attribute_name(:paired_end) %></th>
      <th><%= model_class.human_attribute_name(:distance_cassure) %></th>
      <th><%= model_class.human_attribute_name(:element_id) %></th>
      <th><%= model_class.human_attribute_name(:empcr_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sequencings.each do |sequencing| %>
      <tr>
        <td><%= link_to sequencing.id, sequencing_path(sequencing) %></td>
        <td><%= sequencing.sequencing_name %></td>
        <td><%= sequencing.paired_end %></td>
        <td><%= sequencing.distance_cassure %></td>
        <td><%= sequencing.element_id %></td>
        <td><%= sequencing.empcr_id %></td>
        <td><%=l sequencing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sequencing_path(sequencing), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sequencing_path(sequencing),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sequencing_path,
            :class => 'btn btn-primary' %>

app/views/sequencings/new.html.erb
<%- model_class = @sequencing.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sequencings/show.html.erb
<%- model_class = @sequencing.class -%>




    


<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:sequencing_name) %>:</strong></dt>
  <dd><%= @sequencing.sequencing_name %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@sequencing.element_id).element_date) %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:projet_associé) %>:</strong></dt>
  <dd><%=display_fields_on_views( Element.find(@sequencing.element_id).projects.collect { |a| a.project_name  }.join(",") )%></dd>
  
   <dt><strong><%= model_class.human_attribute_name(:experimentator) %>:</strong></dt>
  <dd><%=display_fields_on_views( Element.find(@sequencing.element_id).users.collect { |a| a.name  }.join(",") )%></dd>
  
  
 
  <dt><strong><%= model_class.human_attribute_name(:paired_end) %>:</strong></dt>
  <dd><%= display_fields_on_views(@sequencing.paired_end )%></dd>
  <dt><strong><%= model_class.human_attribute_name(:distance_cassure) %>:</strong></dt>
  <dd><%= display_fields_on_views(@sequencing.distance_cassure) %></dd>
 
  <dt><strong><%= model_class.human_attribute_name(:empcr_associé) %>:</strong></dt>
  <dd><%= display_fields_on_views(@sequencing.empcr_assoc) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back_to_index', :default => t("helpers.links.back_to_index")),
              elements_path, :class => 'btn'  %>
  <%= link_to t('.edit_further', :default => t("helpers.links.edit_further")),
              edit_sequencing_path(@sequencing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sequencing_path(@sequencing),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>