config/routes.rb
Limsv1::Application.routes.draw do
  
  devise_for :users

  resources :spectros

  resources :rnaseqs

  resources :seizespyros

  resources :metagenomes

  resources :genomes

  resources :data

  resources :submissions

  resources :sequencings

  resources :em_pcrs

  resources :libraries

  resources :extractions

  get "cultures/show"
  
  resources :cultures
  
  

  resources :experiments
  resources :elements 

  resources :users

  resources :projects
  resources :home
  
 
  get "home/index"
  get "projects/destroy"

root :to => 'home#index'

end

app/models/spectro.rb
class Spectro < ActiveRecord::Base
  belongs_to :element 
  attr_accessible :analyse_type, :attached_files, :comments, :culture_assoc, :element_id, :gel_number, :probe_number, :procedure, :sample_type, :samples_number, :spectro_name


 validates_presence_of :culture_assoc
 
 #see  form_edit
def display_name
 "#{spectro_name}"
end
 

end

app/controllers/spectros_controller.rb
class SpectrosController < ApplicationController
   #helper from devise
  before_filter :authenticate_user!
  
  
      #cancan permet d'afficher uniqeuement si authoriser dans ability.rb
 load_and_authorize_resource
  
  # GET /spectros
  # GET /spectros.json
  def index
    @spectros = Spectro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spectros }
    end
  end

  # GET /spectros/1
  # GET /spectros/1.json
  def show
    @spectro = Spectro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spectro }
    end
  end

  # GET /spectros/new
  # GET /spectros/new.json
  def new
    @spectro = Spectro.new
    
       #params :elt from elementcontroller
     @project_associe_id=params[:elt][:cp]  # va servir ds spectro _form view
      @e=params[:elt] 
      @e.delete(:cp)      
    flash[:elt]=@e  #from elementcontroller used for next action :create
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spectro }
    end
  end

  # GET /spectros/1/edit
  def edit
    @spectro = Spectro.find(params[:id])
  end

  # POST /spectros
  # POST /spectros.json
  def create
    @spectro = Spectro.new(params[:spectro])
    
   @elt=flash[:elt]
    @element = Element.new(@elt)
     @element.element_name=@spectro.spectro_name
     
    #cf uniqueness of element_name ds model
    if  ! (@element.valid?)
      if (@element.projects.blank?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
      else
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! name already used '
        return
         end
    end
    
       #cf presence of _assoc ds model
    if  ! (@spectro.valid?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
    end
    
    
    @element.save    
    #@spectro.spectro_name=flash[:elt][:element_name] 
    #permet d'associer elt a spectro pour projet::detail elt
    @spectro.element_id= Element.last.id

    respond_to do |format|
      if @spectro.save
        format.html { redirect_to @spectro, notice: 'Spectro was successfully created.' }
        format.json { render json: @spectro, status: :created, location: @spectro }
      else
        format.html { render action: "new" }
        format.json { render json: @spectro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spectros/1
  # PUT /spectros/1.json
  def update
    @spectro = Spectro.find(params[:id])

    respond_to do |format|
      if @spectro.update_attributes(params[:spectro])
        format.html { redirect_to @spectro, notice: 'Spectro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spectro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spectros/1
  # DELETE /spectros/1.json
  def destroy
    @spectro = Spectro.find(params[:id])
    @spectro.destroy

    respond_to do |format|
      format.html { redirect_to spectros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spectros_helper.rb
module SpectrosHelper
end

app/views/spectros/_form.html.erb
<%= semantic_form_for @spectro, :html => { :class => 'form-horizontal' } do |f| %>

  
 <div class="control-group">
    <%= f.label :spectro_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :spectro_name, :class => 'text_field'  %>
    </div>
  </div>
 
 
  <div class="control-group">    
    <div class="controls">
     <!--method ds helper -->
    <%= f.input :culture_assoc, :as => :radio, :collection => filtre_elt_associe(@project_associe_id,"culture") %>       
    </div>
  </div>
 
 
  <div class="control-group">
    <%= f.label :probe_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :probe_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :analyse_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :analyse_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sample_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sample_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :attached_files, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :attached_files, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :samples_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :samples_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gel_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :gel_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :procedure, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :procedure, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comments, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                spectros_path, :class => 'btn' %>
  </div>
<% end %>

app/views/spectros/_form_edit.html.erb
<%= semantic_form_for @spectro, :html => { :class => 'form-horizontal' } do |f| %>

  
 <div class="control-group">
    <%= f.label :spectro_name, :class => 'control-label' %>
    <div class="controls">
      <%= @spectro.spectro_name %>
    </div>
  </div>
 
 
  <div class="control-group">    
    <div class="controls">
     <!--method ds helper -->
    <%= f.input :culture_assoc, :as => :radio, :collection => Culture.all.collect {|el| el.culture_name}
 %>       
    </div>
  </div>
 
 
  <div class="control-group">
    <%= f.label :probe_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :probe_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :analyse_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :analyse_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sample_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sample_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :attached_files, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :attached_files, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :samples_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :samples_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gel_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :gel_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :procedure, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :procedure, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comments, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
               elements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/spectros/edit.html.erb
<%- model_class = @spectro.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/spectros/index.html.erb
<%- model_class = Spectro.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:spectro_name) %></th>
      <th><%= model_class.human_attribute_name(:culture_id) %></th>
      <th><%= model_class.human_attribute_name(:element_id) %></th>
      <th><%= model_class.human_attribute_name(:probe_number) %></th>
      <th><%= model_class.human_attribute_name(:analyse_type) %></th>
      <th><%= model_class.human_attribute_name(:sample_type) %></th>
      <th><%= model_class.human_attribute_name(:attached_files) %></th>
      <th><%= model_class.human_attribute_name(:samples_number) %></th>
      <th><%= model_class.human_attribute_name(:gel_number) %></th>
      <th><%= model_class.human_attribute_name(:procedure) %></th>
      <th><%= model_class.human_attribute_name(:comments) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @spectros.each do |spectro| %>
      <tr>
        <td><%= link_to spectro.id, spectro_path(spectro) %></td>
        <td><%= spectro.spectro_name %></td>
        <td><%= spectro.culture_id %></td>
        <td><%= spectro.element_id %></td>
        <td><%= spectro.probe_number %></td>
        <td><%= spectro.analyse_type %></td>
        <td><%= spectro.sample_type %></td>
        <td><%= spectro.attached_files %></td>
        <td><%= spectro.samples_number %></td>
        <td><%= spectro.gel_number %></td>
        <td><%= spectro.procedure %></td>
        <td><%= spectro.comments %></td>
        <td><%=l spectro.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_spectro_path(spectro), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      spectro_path(spectro),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_spectro_path,
            :class => 'btn btn-primary' %>

app/views/spectros/new.html.erb
<%- model_class = @spectro.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/spectros/show.html.erb
<%- model_class = @spectro.class -%>




<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  
   <dt><strong><%= model_class.human_attribute_name(:spectro_name) %>:</strong></dt>
  <dd><%= @spectro.spectro_name %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@spectro.element_id).element_date) %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:projet_associé) %>:</strong></dt>
  <dd><%=display_fields_on_views( Element.find(@spectro.element_id).projects.collect { |a| a.project_name  }.join(",")) %></dd>
  
   <dt><strong><%= model_class.human_attribute_name(:experimentator) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@spectro.element_id).users.collect { |a| a.name  }.join(",")) %></dd>
  
 
  <dt><strong><%= model_class.human_attribute_name(:culture_assoc) %>:</strong></dt>
  <dd><%=display_fields_on_views( @spectro.culture_assoc) %></dd>
 
  <dt><strong><%= model_class.human_attribute_name(:probe_number) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.probe_number) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:analyse_type) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.analyse_type) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sample_type) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.sample_type )%></dd>
  <dt><strong><%= model_class.human_attribute_name(:attached_files) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.attached_files) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:samples_number) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.samples_number)%></dd>
  <dt><strong><%= model_class.human_attribute_name(:gel_number) %>:</strong></dt>
  <dd><%=display_fields_on_views( @spectro.gel_number) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:procedure) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.procedure )%></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= display_fields_on_views(@spectro.comments) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back_to_index', :default => t("helpers.links.back_to_index")),
              spectros_path, :class => 'btn'  %>
  <%= link_to t('.edit_further', :default => t("helpers.links.edit_further")),
              edit_spectro_path(@spectro), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              spectro_path(@spectro),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>