config/routes.rb
Limsv1::Application.routes.draw do
  
  devise_for :users

  resources :spectros

  resources :rnaseqs

  resources :seizespyros

  resources :metagenomes

  resources :genomes

  resources :data

  resources :submissions

  resources :sequencings

  resources :em_pcrs

  resources :libraries

  resources :extractions

  get "cultures/show"
  
  resources :cultures
  
  

  resources :experiments
  resources :elements 

  resources :users

  resources :projects
  resources :home
  
 
  get "home/index"
  get "projects/destroy"

root :to => 'home#index'

end

app/models/em_pcr.rb
class EmPcr < ActiveRecord::Base
  belongs_to :element  
  attr_accessible :EM_PCR_name, :PCR_round, :element_id, :library_assoc
  
  
   validates_presence_of :library_assoc

  
  #see empcr form_edit
def display_name
 "#{EM_PCR_name}"
end
  
end

app/controllers/em_pcrs_controller.rb
class EmPcrsController < ApplicationController
  
   #helper from devise
  before_filter :authenticate_user!
  
  
      #cancan permet d'afficher uniqeuement si authoriser dans ability.rb
 load_and_authorize_resource
  
  # GET /em_pcrs
  # GET /em_pcrs.json
  def index
    @em_pcrs = EmPcr.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @em_pcrs }
    end
  end

  # GET /em_pcrs/1
  # GET /em_pcrs/1.json
  def show
    @em_pcr = EmPcr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @em_pcr }
    end
  end

  # GET /em_pcrs/new
  # GET /em_pcrs/new.json
  def new
    @em_pcr = EmPcr.new
    
      #params :elt from elementcontroller
     @project_associe_id=params[:elt][:cp]  # va servir ds extraction _form view
      @e=params[:elt] 
      @e.delete(:cp)      
    flash[:elt]=@e  #from elementcontroller used for next action :create

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @em_pcr }
    end
  end

  # GET /em_pcrs/1/edit
  def edit
    @em_pcr = EmPcr.find(params[:id])
  end

  # POST /em_pcrs
  # POST /em_pcrs.json
 
  
   #renseigne l'id de l element associé...si em-pcr n est pas sauvé, l'element nouvellement cree est effacé
  
  def create
    @em_pcr = EmPcr.new(params[:em_pcr])
    
    
    @elt=flash[:elt]
    @element = Element.new(@elt)
     @element.element_name=@em_pcr.EM_PCR_name
    
    #cf uniqueness of element_name ds model
    if  ! (@element.valid?)
      if (@element.projects.blank?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
      else
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! name already used '
        return
        
     
    end
    end
     
        #cf presence of _assoc ds model
    if  ! (@em_pcr.valid?)
        redirect_to :controller => 'elements', :action => 'new', :notice => ' element has not been saved! make sure all required fields (*) has been filled '
        return
    end
     
    @element.save    
   # @em_pcr.EM_PCR_name=flash[:elt][:element_name] 
    
    
    
    
     #permet d'associer elt a em_pcr pour projet::detail elt
    @em_pcr.element_id= Element.last.id

    respond_to do |format|
      if @em_pcr.save
        format.html { redirect_to @em_pcr, notice: 'Em pcr was successfully created.' }
        format.json { render json: @em_pcr, status: :created, location: @em_pcr }
      else
     
        format.html { render action: "new" }
        format.json { render json: @em_pcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /em_pcrs/1
  # PUT /em_pcrs/1.json
  def update
    @em_pcr = EmPcr.find(params[:id])

    respond_to do |format|
      if @em_pcr.update_attributes(params[:em_pcr])
        format.html { redirect_to @em_pcr, notice: 'Em pcr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @em_pcr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /em_pcrs/1
  # DELETE /em_pcrs/1.json
  def destroy
    @em_pcr = EmPcr.find(params[:id])
    @em_pcr.destroy

    respond_to do |format|
      format.html { redirect_to em_pcrs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/em_pc_rs_helper.rb
module EmPcRsHelper
end

app/views/em_pcrs/_form.html.erb
<%= semantic_form_for @em_pcr, :html => { :class => 'form-horizontal' } do |f| %>
  
  
  <div class="control-group">
    <%= f.label :EM_PCR_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :EM_PCR_name, :class => 'text_field'  %>
    </div>
  </div>
  
  <div class="control-group">
  
    <div class="controls">
       <!--method ds helper -->
    <%= f.input :library_assoc, :as => :radio, :collection => filtre_elt_associe(@project_associe_id,"library") %>
    </div>
  </div>
  <div class="control-group">
    
    <div class="controls">
       
      <%= f.input :PCR_round, :as => :radio, :collection => ["1st round","2nd round"] %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                elements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/em_pcrs/_form_edit.html.erb
<%= semantic_form_for @em_pcr, :html => { :class => 'form-horizontal' } do |f| %>
  
  
  <div class="control-group">
    <%= f.label :EM_PCR_name, :class => 'control-label' %>
    <div class="controls">
      <%= @em_pcr.EM_PCR_name %>
    </div>
  </div>
  
  <div class="control-group">
  
    <div class="controls">
       <!--method ds helper -->
    <%= f.input :library_assoc, :as => :radio, :collection => Library.all.collect {|el| el.library_name}
 %>
    </div>
  </div>
  <div class="control-group">
    
    <div class="controls">
       
      <%= f.input :PCR_round, :as => :radio, :collection => ["1st round","2nd round"] %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                elements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/em_pcrs/edit.html.erb
<%- model_class = @em_pcr.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/em_pcrs/index.html.erb
<%- model_class = EmPcr.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:EM_PCR_name) %></th>
      <th><%= model_class.human_attribute_name(:PCR_round) %></th>
      <th><%= model_class.human_attribute_name(:element_id) %></th>
      <th><%= model_class.human_attribute_name(:library_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @em_pcrs.each do |em_pcr| %>
      <tr>
        <td><%= link_to em_pcr.id, em_pcr_path(em_pcr) %></td>
        <td><%= em_pcr.EM_PCR_name %></td>
        <td><%= em_pcr.PCR_round %></td>
        <td><%= em_pcr.element_id %></td>
        <td><%= em_pcr.library_id %></td>
        <td><%=l em_pcr.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_em_pcr_path(em_pcr), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      em_pcr_path(em_pcr),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_em_pcr_path,
            :class => 'btn btn-primary' %>

app/views/em_pcrs/new.html.erb
<%- model_class = @em_pcr.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/em_pcrs/show.html.erb
<%- model_class = @em_pcr.class -%>


   


<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
 <dt><strong><%= model_class.human_attribute_name(:EM_PCR_name) %>:</strong></dt>
  <dd><%= @em_pcr.EM_PCR_name %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@em_pcr.element_id).element_date) %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:projet_associé) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@em_pcr.element_id).projects.collect { |a| a.project_name  }.join(",")) %></dd>
  
   <dt><strong><%= model_class.human_attribute_name(:experimentator) %>:</strong></dt>
  <dd><%= display_fields_on_views(Element.find(@em_pcr.element_id).users.collect { |a| a.name  }.join(",")) %></dd>
  
  
  <dt><strong><%= model_class.human_attribute_name(:PCR_round) %>:</strong></dt>
  <dd><%= display_fields_on_views(@em_pcr.PCR_round) %></dd>
 
  <dt><strong><%= model_class.human_attribute_name(:library_id) %>:</strong></dt>
  <dd><%= display_fields_on_views(@em_pcr.library_assoc) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back_to_index', :default => t("helpers.links.back_to_index")),
              elements_path, :class => 'btn'  %>
  <%= link_to t('.edit_further', :default => t("helpers.links.edit_further")),
              edit_em_pcr_path(@em_pcr), :class => 'btn' %>
 
</div>