config/routes.rb
Limsv1::Application.routes.draw do
  
  devise_for :users

  resources :spectros

  resources :rnaseqs

  resources :seizespyros

  resources :metagenomes

  resources :genomes

  resources :data

  resources :submissions

  resources :sequencings

  resources :em_pcrs

  resources :libraries

  resources :extractions

  get "cultures/show"
  
  resources :cultures
  
  

  resources :experiments
  resources :elements 

  resources :users

  resources :projects
  resources :home
  
 
  get "home/index"
  get "projects/destroy"

root :to => 'home#index'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base

belongs_to :element
  
has_many :welldish_experiments
has_many :welldishs, :through => :welldish_experiments

attr_accessible :exptype, :resultfile, :element_id
def display_name
"#{exptype}"
end




end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])
    

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
       
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/views/experiments/_form.html.erb
<%= semantic_form_for @experiment do |f| %>
  <%= f.inputs do %>
    <%= f.input :exptype %>
  <% end %>
    
    <%= f.actions :submit, :cancel %>
    

  <% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>






<%= render 'form' %>



<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<h1>Listing experiments</h1>

<table>
  <tr>

    <th>name</th>
  
  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experiments.each do |experiment| %>
  <tr>
    
    <td><%= experiment.exptype%></td>
   
    
   
  
    <td><%= link_to 'Show', experiment %></td>
    <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
    <td><%= link_to 'Destroy', experiment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>exptype:</b>
  <%= @experiment.exptype %>
</p>








<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>